-- DropForeignKey
ALTER TABLE "VC" DROP CONSTRAINT "VCSocial_VC_ID";

-- AddForeignKey
ALTER TABLE "VC" ADD CONSTRAINT "VCSocial_VC_ID" FOREIGN KEY ("Id") REFERENCES "VCSocial"("Id") ON DELETE CASCADE ON UPDATE CASCADE;
